version: "3.8"

services:
  notifications:
    container_name: notifications
    environment:
      - PORT=${PORT}
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    expose:
      - '${PORT}'
    ports:
      - '${PORT}:${PORT}'
    command: npm run start
