version: "3.8"

services:
  notifications:
    container_name: notifications
    environment:
      - PORT=${PORT}
      - HOST=${HOST}
      - DB_URI=${DB_URI}
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    expose:
      - 7777
    ports:
      - 7777:7777
    command: npm run start
