# fly.toml file generated for fiufit-notifications on 2023-05-27T21:30:52-03:00

app = "fiufit-notifications"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "eze"
processes = []

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = false
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
[env]
  PORT = "8080"
  HOST = "0.0.0.0"
