name: Okteto deploy

on:
  push: 
    branches: [main]    
jobs:
  deploy:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Login to Okteto Cloud
        uses: okteto/context@latest
        with:
          token: ${{ secrets.OKTETO_TOKEN }}
          
      - name: Create devlopment environments namespace
        uses: okteto/namespace@latest
        with:
          namespace: notifications-danielovera

      - name: "Build"
        uses: okteto/build@latest
          
