name: Okteto deploy

on:
  push: 
    branches: [main]
  pull_request:
    branches: [main]
    
jobs:
  deploy:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Login to Okteto Cloud
        uses: okteto/context@2.12.0
        with:
          token: ${{ secrets.OKTETO_TOKEN }}

      - if: ${{ github.event_name == 'push' }}
        name: Build and deploy application container
        uses: okteto/build@latest
