name: Okteto deploy

on:
  push: 
    branches: [main]    
jobs:
  deploy:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Login to Okteto Cloud
        uses: okteto/context@latest
        with:
          token: ${{ secrets.OKTETO_TOKEN }}

      - uses: okteto/namespace@latest
        with:
          namespace: notifications-danielovera

      - name: Build and deploy application container
        uses: okteto/deploy-stack@2.12.0
        with:
          namespace: notifications-danielovera
          build: "true"
          
